"""Initial migration with all tables

Revision ID: f84416d23e66
Revises: 
Create Date: 2025-10-24 11:49:06.477146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f84416d23e66'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False, comment='関係機関ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='機関名'),
    sa.Column('type', sa.String(length=50), nullable=False, comment='種別（サービス事業所/医療機関/後見人/その他）'),
    sa.Column('postal_code', sa.String(length=10), nullable=True, comment='郵便番号'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='住所'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('fax', sa.String(length=20), nullable=True, comment='FAX番号'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='メールアドレス'),
    sa.Column('contact_person', sa.String(length=100), nullable=True, comment='担当者氏名'),
    sa.Column('contact_person_phone', sa.String(length=20), nullable=True, comment='担当者電話番号'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_type'), 'organizations', ['type'], unique=False)
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), nullable=False, comment='スタッフID'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='ログインユーザー名'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='パスワードハッシュ'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='氏名'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='権限 (admin/staff)'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='メールアドレス'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='有効フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staffs_id'), 'staffs', ['id'], unique=False)
    op.create_index(op.f('ix_staffs_username'), 'staffs', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='利用者ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='氏名'),
    sa.Column('name_kana', sa.String(length=100), nullable=True, comment='氏名（カナ）'),
    sa.Column('birth_date', sa.Date(), nullable=False, comment='生年月日'),
    sa.Column('gender', sa.String(length=10), nullable=True, comment='性別'),
    sa.Column('postal_code', sa.String(length=10), nullable=True, comment='郵便番号'),
    sa.Column('address', sa.String(length=255), nullable=True, comment='住所'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='電話番号'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='メールアドレス'),
    sa.Column('emergency_contact_name', sa.String(length=100), nullable=True, comment='緊急連絡先氏名'),
    sa.Column('emergency_contact_phone', sa.String(length=20), nullable=True, comment='緊急連絡先電話番号'),
    sa.Column('disability_support_level', sa.Integer(), nullable=True, comment='障害支援区分 (1-6)'),
    sa.Column('disability_support_certified_date', sa.Date(), nullable=True, comment='障害支援区分認定日'),
    sa.Column('disability_support_expiry_date', sa.Date(), nullable=True, comment='障害支援区分有効期限'),
    sa.Column('guardian_type', sa.String(length=50), nullable=True, comment='後見人種別（成年後見人/保佐人/補助人）'),
    sa.Column('guardian_name', sa.String(length=100), nullable=True, comment='後見人氏名'),
    sa.Column('guardian_contact', sa.String(length=255), nullable=True, comment='後見人連絡先'),
    sa.Column('assigned_staff_id', sa.Integer(), nullable=True, comment='担当スタッフID'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['assigned_staff_id'], ['staffs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_assigned_staff_id'), 'users', ['assigned_staff_id'], unique=False)
    op.create_index(op.f('ix_users_birth_date'), 'users', ['birth_date'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_deleted'), 'users', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_table('consultations',
    sa.Column('id', sa.Integer(), nullable=False, comment='相談記録ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='利用者ID'),
    sa.Column('staff_id', sa.Integer(), nullable=False, comment='対応スタッフID'),
    sa.Column('consultation_date', sa.Date(), nullable=False, comment='相談日'),
    sa.Column('consultation_type', sa.String(length=20), nullable=False, comment='相談形態（来所/訪問/電話/その他）'),
    sa.Column('content', sa.Text(), nullable=False, comment='相談内容'),
    sa.Column('response', sa.Text(), nullable=True, comment='対応内容'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consultations_staff_date', 'consultations', ['staff_id', 'consultation_date'], unique=False)
    op.create_index('idx_consultations_user_date', 'consultations', ['user_id', 'consultation_date'], unique=False)
    op.create_index(op.f('ix_consultations_consultation_date'), 'consultations', ['consultation_date'], unique=False)
    op.create_index(op.f('ix_consultations_id'), 'consultations', ['id'], unique=False)
    op.create_index(op.f('ix_consultations_staff_id'), 'consultations', ['staff_id'], unique=False)
    op.create_index(op.f('ix_consultations_user_id'), 'consultations', ['user_id'], unique=False)
    op.create_table('notebooks',
    sa.Column('id', sa.Integer(), nullable=False, comment='手帳ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='利用者ID'),
    sa.Column('notebook_type', sa.String(length=50), nullable=False, comment='手帳種別（療育手帳/精神障害者保健福祉手帳）'),
    sa.Column('grade', sa.String(length=20), nullable=True, comment='等級・程度'),
    sa.Column('issue_date', sa.Date(), nullable=True, comment='交付日'),
    sa.Column('renewal_date', sa.Date(), nullable=True, comment='更新日'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notebooks_id'), 'notebooks', ['id'], unique=False)
    op.create_index(op.f('ix_notebooks_user_id'), 'notebooks', ['user_id'], unique=False)
    op.create_table('plans',
    sa.Column('id', sa.Integer(), nullable=False, comment='計画ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='利用者ID'),
    sa.Column('staff_id', sa.Integer(), nullable=False, comment='作成者スタッフID'),
    sa.Column('plan_type', sa.String(length=20), nullable=False, comment='計画種別（初回/更新）'),
    sa.Column('plan_number', sa.String(length=50), nullable=True, comment='計画番号（例: 2025-001）'),
    sa.Column('created_date', sa.Date(), nullable=False, comment='計画作成日'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='計画開始日'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='計画終了日'),
    sa.Column('current_situation', sa.Text(), nullable=True, comment='現在の状況'),
    sa.Column('hopes_and_needs', sa.Text(), nullable=True, comment='本人・家族の希望やニーズ'),
    sa.Column('support_policy', sa.Text(), nullable=True, comment='総合的な援助方針'),
    sa.Column('long_term_goal', sa.Text(), nullable=True, comment='長期目標'),
    sa.Column('long_term_goal_period', sa.String(length=50), nullable=True, comment='長期目標期間（例: 6ヶ月）'),
    sa.Column('short_term_goal', sa.Text(), nullable=True, comment='短期目標'),
    sa.Column('short_term_goal_period', sa.String(length=50), nullable=True, comment='短期目標期間（例: 3ヶ月）'),
    sa.Column('services', sa.JSON(), nullable=True, comment='サービス内容（JSON形式）'),
    sa.Column('approval_status', sa.String(length=20), nullable=False, comment='承認状況（作成中/承認済み/実施中/終了）'),
    sa.Column('approval_date', sa.Date(), nullable=True, comment='承認日'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_approval_status'), 'plans', ['approval_status'], unique=False)
    op.create_index(op.f('ix_plans_end_date'), 'plans', ['end_date'], unique=False)
    op.create_index(op.f('ix_plans_id'), 'plans', ['id'], unique=False)
    op.create_index(op.f('ix_plans_is_deleted'), 'plans', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_plans_plan_number'), 'plans', ['plan_number'], unique=True)
    op.create_index(op.f('ix_plans_staff_id'), 'plans', ['staff_id'], unique=False)
    op.create_index(op.f('ix_plans_start_date'), 'plans', ['start_date'], unique=False)
    op.create_index(op.f('ix_plans_user_id'), 'plans', ['user_id'], unique=False)
    op.create_table('user_organizations',
    sa.Column('id', sa.Integer(), nullable=False, comment='ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='利用者ID'),
    sa.Column('organization_id', sa.Integer(), nullable=False, comment='関係機関ID'),
    sa.Column('relationship_type', sa.String(length=50), nullable=True, comment='関係種別（通所/入院/主治医/後見人など）'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='利用開始日'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='利用終了日'),
    sa.Column('frequency', sa.String(length=50), nullable=True, comment='頻度（週5日/月2回など）'),
    sa.Column('notes', sa.Text(), nullable=True, comment='備考'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_organizations_user_org', 'user_organizations', ['user_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_user_organizations_id'), 'user_organizations', ['id'], unique=False)
    op.create_index(op.f('ix_user_organizations_organization_id'), 'user_organizations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_organizations_user_id'), 'user_organizations', ['user_id'], unique=False)
    op.create_table('monitorings',
    sa.Column('id', sa.Integer(), nullable=False, comment='モニタリングID'),
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='計画ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='利用者ID'),
    sa.Column('staff_id', sa.Integer(), nullable=False, comment='実施者スタッフID'),
    sa.Column('monitoring_date', sa.Date(), nullable=False, comment='モニタリング実施日'),
    sa.Column('monitoring_type', sa.String(length=20), nullable=False, comment='モニタリング種別（定期/随時）'),
    sa.Column('service_usage_status', sa.Text(), nullable=True, comment='サービス利用状況'),
    sa.Column('goal_achievement', sa.Text(), nullable=True, comment='目標達成状況'),
    sa.Column('satisfaction', sa.String(length=20), nullable=True, comment='満足度（満足/やや満足/普通/やや不満/不満）'),
    sa.Column('changes_in_needs', sa.Text(), nullable=True, comment='ニーズの変化'),
    sa.Column('issues_and_concerns', sa.Text(), nullable=True, comment='課題・問題点'),
    sa.Column('future_policy', sa.Text(), nullable=True, comment='今後の方針'),
    sa.Column('plan_revision_needed', sa.Boolean(), nullable=False, comment='計画変更の必要性'),
    sa.Column('next_monitoring_date', sa.Date(), nullable=True, comment='次回モニタリング予定日'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='削除フラグ'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='作成日時'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='更新日時'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitorings_id'), 'monitorings', ['id'], unique=False)
    op.create_index(op.f('ix_monitorings_is_deleted'), 'monitorings', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_monitorings_monitoring_date'), 'monitorings', ['monitoring_date'], unique=False)
    op.create_index(op.f('ix_monitorings_next_monitoring_date'), 'monitorings', ['next_monitoring_date'], unique=False)
    op.create_index(op.f('ix_monitorings_plan_id'), 'monitorings', ['plan_id'], unique=False)
    op.create_index(op.f('ix_monitorings_staff_id'), 'monitorings', ['staff_id'], unique=False)
    op.create_index(op.f('ix_monitorings_user_id'), 'monitorings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitorings_user_id'), table_name='monitorings')
    op.drop_index(op.f('ix_monitorings_staff_id'), table_name='monitorings')
    op.drop_index(op.f('ix_monitorings_plan_id'), table_name='monitorings')
    op.drop_index(op.f('ix_monitorings_next_monitoring_date'), table_name='monitorings')
    op.drop_index(op.f('ix_monitorings_monitoring_date'), table_name='monitorings')
    op.drop_index(op.f('ix_monitorings_is_deleted'), table_name='monitorings')
    op.drop_index(op.f('ix_monitorings_id'), table_name='monitorings')
    op.drop_table('monitorings')
    op.drop_index(op.f('ix_user_organizations_user_id'), table_name='user_organizations')
    op.drop_index(op.f('ix_user_organizations_organization_id'), table_name='user_organizations')
    op.drop_index(op.f('ix_user_organizations_id'), table_name='user_organizations')
    op.drop_index('idx_user_organizations_user_org', table_name='user_organizations')
    op.drop_table('user_organizations')
    op.drop_index(op.f('ix_plans_user_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_start_date'), table_name='plans')
    op.drop_index(op.f('ix_plans_staff_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_plan_number'), table_name='plans')
    op.drop_index(op.f('ix_plans_is_deleted'), table_name='plans')
    op.drop_index(op.f('ix_plans_id'), table_name='plans')
    op.drop_index(op.f('ix_plans_end_date'), table_name='plans')
    op.drop_index(op.f('ix_plans_approval_status'), table_name='plans')
    op.drop_table('plans')
    op.drop_index(op.f('ix_notebooks_user_id'), table_name='notebooks')
    op.drop_index(op.f('ix_notebooks_id'), table_name='notebooks')
    op.drop_table('notebooks')
    op.drop_index(op.f('ix_consultations_user_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_staff_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_id'), table_name='consultations')
    op.drop_index(op.f('ix_consultations_consultation_date'), table_name='consultations')
    op.drop_index('idx_consultations_user_date', table_name='consultations')
    op.drop_index('idx_consultations_staff_date', table_name='consultations')
    op.drop_table('consultations')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_is_deleted'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_birth_date'), table_name='users')
    op.drop_index(op.f('ix_users_assigned_staff_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_staffs_username'), table_name='staffs')
    op.drop_index(op.f('ix_staffs_id'), table_name='staffs')
    op.drop_table('staffs')
    op.drop_index(op.f('ix_organizations_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
